const bigInt = require("big-integer");

const BLOCK_INTERVAL = 3;
const BLOCKS_PER_YEAR = (365 * 24 * 60 * 60) / BLOCK_INTERVAL;
const BLOCKS_PER_DAY = (24 * 60 * 60) / BLOCK_INTERVAL;
const START_VESTING_BLOCK = BLOCKS_PER_DAY * 7;
const START_MINER_VOTING_BLOCK = BLOCKS_PER_DAY * 30;

const CURATE_APR_PERCENT = 3875;
const CONTENT_APR_PERCENT = 3875;
const LIQUIDITY_APR_PERCENT = 750;
const PRODUCER_APR_PERCENT = 750;
const POW_APR_PERCENT = 750;

const MINING_REWARD = 1000;

const MIN_CURATE_REWARD = MINING_REWARD;
const MIN_CONTENT_REWARD = MINING_REWARD;
const MIN_PRODUCER_REWARD = MINING_REWARD;
const MIN_POW_REWARD = MINING_REWARD;

const APR_PERCENT_MULTIPLY_PER_BLOCK = bigInt(0x5ccc)
  .shiftLeft(0x20)
  .or(bigInt(0xe802).shiftLeft(0x10))
  .or(bigInt(0xde5f));
const APR_PERCENT_SHIFT_PER_BLOCK = 87;

module.exports = {
  BLOCK_INTERVAL,
  BLOCKS_PER_YEAR,
  BLOCKS_PER_DAY,
  START_VESTING_BLOCK,
  START_MINER_VOTING_BLOCK,
  CURATE_APR_PERCENT,
  CONTENT_APR_PERCENT,
  LIQUIDITY_APR_PERCENT,
  PRODUCER_APR_PERCENT,
  POW_APR_PERCENT,
  MINING_REWARD,
  MIN_CURATE_REWARD,
  MIN_CONTENT_REWARD,
  MIN_PRODUCER_REWARD,
  MIN_POW_REWARD,
  APR_PERCENT_MULTIPLY_PER_BLOCK,
  APR_PERCENT_SHIFT_PER_BLOCK
};
